import Head from 'next/head';
import Header from '../Components/Header';
import Upload from '../Components/upload';

export default function Home() {
  return (
    <div>
      <Head>
        <title>projeto | Uploader!</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Upload />
    </div>
  );
}
